FROM wmdailey/security:latest
MAINTAINER WKD

ENV KEYCLOAK_VERSION 11.0.2
ARG KEYCLOAK_DIST=https://downloads.jboss.org/keycloak/$KEYCLOAK_VERSION/keycloak-$KEYCLOAK_VERSION.tar.gz
ENV KEYCLOAKPASS BadPass%1

# Enables signals getting passed from startup script to JVM
# ensuring clean shutdown when container is stopped.
ENV LAUNCH_JBOSS_IN_BACKGROUND 1
ENV PROXY_ADDRESS_FORWARDING false

USER root

# Supporting packages
#RUN yum install -y java-1.8.0-openjdk-devel

# Download and install software
WORKDIR /opt
RUN wget $KEYCLOAK_DIST && \
tar xzf keycloak-$KEYCLOAK_VERSION.tar.gz && \
ln -s keycloak-$KEYCLOAK_VERSION keycloak && \
rm keycloak-$KEYCLOAK_VERSION.tar.gz && \
chmod 755 keycloak-$KEYCLOAK_VERSION

# Systemd
COPY init/keycloak.server /etc/systemd/system/keycloak.service &&\
systemctl enable keycloak
    
# Create a user and group used to launch processes
# The user ID 1000 is the default for the first "regular" user on Fedora/RHEL,
# so there is a high chance that this ID will be equal to the current user
# making it easier to use volumes (no permission issues)
RUN groupadd -r keycloak && \
useradd -r -g keycloak -m -d /var/lib/keycloak -s /sbin/nologin -c "keycloak user" keycloak && \
chown -R keycloak:keycloak keycloak && \\
chmod 700 keycloak/standalone

# Set the working directory to jboss' user home directory
WORKDIR /opt/keycloak
USER keycloak

RUN ./bin/add-user-keycloak.sh --user admin --password KEYCLOAKPASS --realm master

RUN ./bin/jboss-cli.sh 'embed-server,/subsystem=undertow/server=default-server/http-listener=default:write-attribute(name=proxy-address-forwarding,value=true)' && \\
./bin/jboss-cli.sh 'embed-server,/socket-binding-group=standard-sockets/socket-binding=proxy-https:add(port=443)' && \\
./bin/jboss-cli.sh 'embed-server,/subsystem=undertow/server=default-server/http-listener=default:write-attribute(name=redirect-socket,value=proxy-https)'


ADD docker-entrypoint.sh /opt/jboss/

ADD cli /opt/jboss/keycloak/cli
RUN cd /opt/jboss/keycloak && bin/jboss-cli.sh --file=cli/standalone-configuration.cli && rm -rf /opt/jboss/keycloak/standalone/configuration/standalone_xml_history
RUN cd /opt/jboss/keycloak && bin/jboss-cli.sh --file=cli/standalone-ha-configuration.cli && rm -rf /opt/jboss/keycloak/standalone/configuration/standalone_xml_history

ENV JDBC_POSTGRES_VERSION 42.2.2

ADD databases/change-database.sh /opt/jboss/keycloak/bin/change-database.sh

RUN mkdir -p /opt/jboss/keycloak/modules/system/layers/base/org/postgresql/jdbc/main; cd /opt/jboss/keycloak/modules/system/layers/base/org/postgresql/jdbc/main; curl -L http://central.maven.org/maven2/org/postgresql/postgresql/$JDBC_POSTGRES_VERSION/postgresql-$JDBC_POSTGRES_VERSION.jar > postgres-jdbc.jar
ADD databases/postgres/module.xml /opt/jboss/keycloak/modules/system/layers/base/org/postgresql/jdbc/main

ENV JBOSS_HOME /opt/jboss/keycloak
ENV LANG en_US.UTF-8

EXPOSE 8080

ENTRYPOINT [ "/opt/jboss/docker-entrypoint.sh" ]

CMD ["-b", "0.0.0.0"]
